application: journal-ma
version: hazel-cms-3
runtime: python
api_version: 1

handlers:
- url: /admin_console/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /media
  static_dir: media

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /contrib
  static_dir: static/contrib

- url: /test.*
  script: gaeunit.py

- url: /.*
  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$|^contrib/.*$
